bypassText: |
  bypass:
    - localhost
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 172.32.*
    - 172.33.*
    - 192.168.*
    - adguard.jobshen.com
    - <local>
mixinType: 0
proxyOrder: 1
latencyUrl: http://cp.cloudflare.com/generate_204
fontFamily: Noto Sans Mono CJK SC Regular
showNotifications: true
